### ISSUE TITLE
Write unit tests for both packages

### ISSUE THREAD

**Issue by whizkydee** [whizkydee/dropd#4]

**Comment by samie820** [comment]
Hi, I'm pretty new to contributing to monorepos, but I'll like to work on this feature

**Comment by whizkydee** [comment]
Hey @samie820,

That's great! It's nothing really crazy, I left some instructions in the **Contributing** section, feel free to take a look and let me know if you expereince any problems.

**Comment by samie820** [comment]
thanks...followed the instructions, I was having issues with `yarn install -W`, ended up adding a `private: true` property to the package.json (read it on the yarn docs BTW). Also, if i'm setting up jest, do I install it in the `react-dropd` package?

**Comment by whizkydee** [comment]
Perfect! No need to install it in `react-dropd`. Yarn workspaces and lerna manage that. So, just install it in `dropd`.

**Comment by samie820** [comment]
Oh cool, thanks

**Comment by whizkydee** [comment]
Hey @samie820! Please checkout the new codebase. A lot has changed, including bug fixes and browser inconsistencies.

**Comment by samie820** [comment]
Ok will do, I was about to make a PR, but let me check out the changes

**Comment by whizkydee** [comment]
Thanks for the work on this @samie820, I just merged to `master`, and published as `v1.1.1` with a bunch of nice changes.

I've been really busy lately... at the same time, I've been thinking of the best way to test these components, and I'm glad to announce that I've found just the right solution -- **Cypress!**

I'll start the setup and migration this week and most likely publish with support for slots -- #3.
